name: SDG_11.2.1
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - abseil-cpp=20200225.2=he1b5a44_2
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - arrow-cpp=2.0.0=py38ha9d6ab6_6_cpu
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - autopep8=1.5.4=pyh9f0ad1d_0
  - aws-c-common=0.4.59=h36c2ea0_1
  - aws-c-event-stream=0.1.6=had2084c_6
  - aws-checksums=0.1.10=h4e93380_0
  - aws-sdk-cpp=1.8.70=h57dc084_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - boost-cpp=1.74.0=h9359b55_0
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.3=py38h1bdcb99_1
  - cfitsio=3.470=hb418390_7
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - dbus=1.13.6=hfdff14a_1
  - debugpy=1.4.1=py38h709712a_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - fastcore=1.3.16=py_0
  - fastscript=1.0.0=0
  - feather-format=0.4.1=pyh9f0ad1d_0
  - fiona=1.8.17=py38h676c6b2_1
  - flake8=3.8.4=py_0
  - folium=0.12.0=pyhd8ed1ab_1
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - fsspec=2021.8.1=pyhd8ed1ab_0
  - gcsfs=2021.8.1=pyhd8ed1ab_0
  - gdal=3.1.4=py38h9edfc58_0
  - geopandas=0.8.1=py_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h5d11630_3
  - gettext=0.19.8.1=hf34092f_1004
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.66.2=h58526e2_0
  - glog=0.4.0=h49b9bf7_3
  - google-auth=2.0.2=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpc-cpp=1.33.2=h1870a98_1
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=67.1=he1b5a44_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - ipdb=0.13.4=pyhd3deb0d_0
  - ipykernel=6.3.1=py38he5a9106_0
  - ipython=7.27.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.4=pyhd8ed1ab_0
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.13.1=hbfbb72e_1002
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py_2
  - jupyter_client=7.0.2=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.1=pyhd8ed1ab_0
  - kealib=1.4.14=hcc255d8_2
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=11_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcurl=7.71.1=hcdd3856_8
  - libdap4=3.20.6=hd7c4107_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgdal=3.1.4=h670eac6_0
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libglib=2.66.2=hbe7bbb4_0
  - libgomp=11.1.0=hc902ee8_8
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=11_linux64_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libpq=12.3=h5513abc_2
  - libprotobuf=3.13.0.1=h8b12597_0
  - librttopo=1.1.0=hb271727_4
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h6ec7341_0
  - libssh2=1.10.0=ha56f1ee_0
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libthrift=0.13.0=h5aa387f_6
  - libtiff=4.1.0=h4f3a223_6
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-base=3.4.3=py38hf4fb855_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py38h497a2fe_1004
  - multidict=5.1.0=py38h497a2fe_1
  - munch=2.5.0=py_0
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.1.0=py38h578d9bd_0
  - nbdev=0.2.40=pyh39e3cac_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.6.2=pyhd8ed1ab_0
  - notebook=6.4.3=pyha770c72_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numpy=1.19.5=py38h9894fe3_2
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.3.1=hf7af979_3
  - openssl=1.1.1l=h7f98852_0
  - orc=1.6.5=hd3605a7_0
  - osmnx=0.16.1=pyh9f0ad1d_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.2=py38h43a58ef_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py38h9776b28_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - plotly=4.14.1=pyhd3deb0d_0
  - poppler=0.89.0=h669c267_1
  - poppler-data=0.4.10=0
  - postgresql=12.3=h8573dbc_2
  - proj=7.1.1=h966b41f_3
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=2.0.0=py38h5703e5b_6_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38h56787f0_3
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.6=h852b56e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_1
  - pyzmq=22.2.1=py38h2035c66_0
  - qt=5.12.9=h1f2b2cb_0
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.10.0=pyhd8ed1ab_0
  - re2=2020.11.01=h58526e2_0
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - retrying=1.3.3=py_2
  - rope=0.18.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - rtree=0.9.7=py38h02d302b_2
  - scikit-learn=0.24.2=py38h1561384_1
  - scipy=1.7.1=py38h56a6a73_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=57.4.0=py38h578d9bd_0
  - shapely=1.7.1=py38ha11d057_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.36.0=h9cd32fc_0
  - terminado=0.11.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tiledb=2.1.2=h47b529c_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzcode=2021a=h7f98852_2
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - xerces-c=3.2.3=hfe33f54_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
prefix: /usr/local/Caskroom/miniconda/base/envs/SDG_11.2.1
